apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fined-mentor-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/maxwell-tchiabe/fined-mentor.git
    targetRevision: HEAD
    path: infrastructure
  destination: 
    server: https://kubernetes.default.svc
    namespace: fined-mentor

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true