services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - fined-mentor-network

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=${MONGO_URI}
      - GOOGLE_GENAI_API_KEY=${GOOGLE_GENAI_API_KEY}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
    networks:
      - fined-mentor-network

networks:
  fined-mentor-network:
    driver: bridge
